-- Applied to Supabase project hcbxxrvtsldzodpjlvem
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null default 'سپهر',
  created_at timestamptz not null default now()
);

create table if not exists public.player_state (
  user_id uuid primary key references auth.users(id) on delete cascade,
  level integer not null default 1,
  xp integer not null default 0,
  coins integer not null default 100,
  stars integer not null default 0,
  current_quest text not null default 'level_1_barter',
  updated_at timestamptz not null default now()
);

create table if not exists public.skills (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  skill_key text not null,
  score numeric(3,2) not null default 0,
  evidence_count integer not null default 0,
  updated_at timestamptz not null default now(),
  unique (user_id, skill_key)
);

create table if not exists public.quest_progress (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  quest_key text not null,
  status text not null default 'locked',
  state jsonb not null default '{}'::jsonb,
  completed_at timestamptz,
  updated_at timestamptz not null default now(),
  unique (user_id, quest_key)
);

create table if not exists public.decisions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  quest_key text not null,
  decision_key text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.wallet_transactions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  delta integer not null,
  balance_after integer not null,
  reason text not null,
  quest_key text,
  created_at timestamptz not null default now()
);

create table if not exists public.ai_interactions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  quest_key text,
  request_kind text not null,
  input_context jsonb not null default '{}'::jsonb,
  output jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
